### ISSUE TITLE
Hilfefenster: Tutorial- und Sandboxhilfetexte sind noch buggy

### ISSUE THREAD

**Issue by DaDings2020** [Kllngii/Lernsoftware#22]
Wirkt so, als wäre da Text hineingeraten, der da nicht reingehört

**Comment by Kllngii** [comment]
Hilfe -> Liniendiagramm ist noch Work in Progress, hier sollte Inhalt ergänzt werden

**Comment by Kllngii** [comment]
geschlossen, da WIP in Issue #20 behandelt wird
